/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CategoryId = IDL.Nat;
export const TipId = IDL.Nat;
export const InvestmentCategory = IDL.Record({
  'id' : CategoryId,
  'icon' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'trendLabel' : IDL.Text,
});
export const InvestmentTip = IDL.Record({
  'id' : TipId,
  'title' : IDL.Text,
  'body' : IDL.Text,
  'category' : CategoryId,
});
export const MarketTrend = IDL.Record({
  'id' : IDL.Text,
  'value' : IDL.Float64,
  'momentum' : IDL.Float64,
});

export const idlService = IDL.Service({
  'addCategory' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [CategoryId],
      [],
    ),
  'addTip' : IDL.Func([IDL.Text, IDL.Text, CategoryId], [TipId], []),
  'getAllCategories' : IDL.Func([], [IDL.Vec(InvestmentCategory)], ['query']),
  'getAllTips' : IDL.Func([], [IDL.Vec(InvestmentTip)], ['query']),
  'getMarketTrends' : IDL.Func([], [IDL.Vec(MarketTrend)], ['query']),
  'getTipsByCategory' : IDL.Func(
      [CategoryId],
      [IDL.Vec(InvestmentTip)],
      ['query'],
    ),
  'subscribeEmail' : IDL.Func([IDL.Text], [], []),
  'updateMarketTrend' : IDL.Func([IDL.Text, IDL.Float64, IDL.Float64], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CategoryId = IDL.Nat;
  const TipId = IDL.Nat;
  const InvestmentCategory = IDL.Record({
    'id' : CategoryId,
    'icon' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'trendLabel' : IDL.Text,
  });
  const InvestmentTip = IDL.Record({
    'id' : TipId,
    'title' : IDL.Text,
    'body' : IDL.Text,
    'category' : CategoryId,
  });
  const MarketTrend = IDL.Record({
    'id' : IDL.Text,
    'value' : IDL.Float64,
    'momentum' : IDL.Float64,
  });
  
  return IDL.Service({
    'addCategory' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [CategoryId],
        [],
      ),
    'addTip' : IDL.Func([IDL.Text, IDL.Text, CategoryId], [TipId], []),
    'getAllCategories' : IDL.Func([], [IDL.Vec(InvestmentCategory)], ['query']),
    'getAllTips' : IDL.Func([], [IDL.Vec(InvestmentTip)], ['query']),
    'getMarketTrends' : IDL.Func([], [IDL.Vec(MarketTrend)], ['query']),
    'getTipsByCategory' : IDL.Func(
        [CategoryId],
        [IDL.Vec(InvestmentTip)],
        ['query'],
      ),
    'subscribeEmail' : IDL.Func([IDL.Text], [], []),
    'updateMarketTrend' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Float64],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };